version: '3'

volumes:
  pg_data_kittygram:
  static:
  media:

services:
  db_kittygram:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data_kittygram:/var/lib/postgresql/data

  backend:
    image: paveldubanenko/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/app2/media/cats/images/

  frontend:
    env_file: .env
    image: paveldubanenko/kittygram_frontend
    command: cp -r /app2/build/. /frontend_static/
    volumes:
      - static:/frontend_static
      
  gateway:
    image: paveldubanenko/kittygram_gateway
    env_file: .env
    volumes:
      - static:/staticfiles
      - media:/media/cats/images/
    ports:
      - 9000:80
    
